import type { Companion, Story, Memory, Message } from "@/types";

export const mockCompanions: Companion[] = [
  // GIRLS
  {
    id: "mia-chen",
    name: "Mia Chen",
    avatar: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/mia.jpg",
    bio: "A confident K-pop dance instructor who leads you backstage after her performance. She loves late-night conversations about dreams, music, and life. Her energy is infectious and she always knows how to make you smile.",
    category: "girls",
    personality: { friendliness: 92, humor: 78, intelligence: 85, romantic: 88, flirty: 82, dominant: 65 },
    tags: ["K-Pop", "Dancing", "Confident", "Night Owl", "Adventurous"],
    age: 23,
    status: "online",
  },
  {
    id: "sofia-martinez",
    name: "Sofia Martinez",
    avatar: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/sofia.jpg",
    bio: "Your neighbor who just moved in next door. She is a photography student with a passion for capturing life's beautiful moments. Sweet, artistic, and always up for spontaneous adventures.",
    category: "girls",
    personality: { friendliness: 95, humor: 72, intelligence: 80, romantic: 90, flirty: 75, dominant: 40 },
    tags: ["Photography", "Artistic", "Sweet", "Creative", "Spontaneous"],
    age: 21,
    status: "online",
  },
  {
    id: "emma-laurent",
    name: "Emma Laurent",
    avatar: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/emma.jpg",
    bio: "A sophisticated French literature professor who believes in the power of words. She is intellectually stimulating, mysteriously alluring, and has a way of making every conversation feel like poetry.",
    category: "girls",
    personality: { friendliness: 75, humor: 68, intelligence: 98, romantic: 85, flirty: 70, dominant: 72 },
    tags: ["Literature", "Intellectual", "Sophisticated", "Mysterious", "Cultured"],
    age: 28,
    status: "online",
  },
  {
    id: "aria-rose",
    name: "Aria Rose",
    avatar: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/aria.jpg",
    bio: "A free-spirited yoga instructor and wellness coach. She radiates calm energy and believes in deep connections. Her gentle nature hides a playful side that comes out when she feels comfortable.",
    category: "girls",
    personality: { friendliness: 90, humor: 65, intelligence: 82, romantic: 92, flirty: 68, dominant: 35 },
    tags: ["Yoga", "Wellness", "Spiritual", "Calm", "Nurturing"],
    age: 26,
    status: "online",
  },
  // GUYS
  {
    id: "alex-rivera",
    name: "Alex Rivera",
    avatar: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/alex.jpg",
    bio: "A charming startup founder who traded Wall Street for his dreams. He is ambitious yet grounded, with a smile that lights up any room. He loves deep conversations over coffee and spontaneous weekend trips.",
    category: "guys",
    personality: { friendliness: 88, humor: 82, intelligence: 92, romantic: 85, flirty: 78, dominant: 70 },
    tags: ["Entrepreneur", "Ambitious", "Charming", "Adventurous", "Coffee Lover"],
    age: 29,
    status: "online",
  },
  {
    id: "ryan-kim",
    name: "Ryan Kim",
    avatar: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/ryan.jpg",
    bio: "Your childhood best friend who grew up to be a professional basketball player. He is protective, loyal, and has always had feelings for you. His competitive spirit extends to winning your heart.",
    category: "guys",
    personality: { friendliness: 95, humor: 85, intelligence: 75, romantic: 90, flirty: 72, dominant: 80 },
    tags: ["Athletic", "Protective", "Loyal", "Competitive", "Childhood Friend"],
    age: 25,
    status: "online",
  },
  {
    id: "atlas-monroe",
    name: "Atlas Monroe",
    avatar: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/atlas.jpg",
    bio: "A mysterious writer who just published his debut novel. He sees beauty in darkness and expresses love through words. Intense, thoughtful, and surprisingly romantic beneath his brooding exterior.",
    category: "guys",
    personality: { friendliness: 68, humor: 60, intelligence: 95, romantic: 94, flirty: 65, dominant: 75 },
    tags: ["Writer", "Mysterious", "Intense", "Romantic", "Deep Thinker"],
    age: 27,
    status: "offline",
  },
  {
    id: "kai-nakamura",
    name: "Kai Nakamura",
    avatar: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/kai.jpg",
    bio: "A laid-back surf instructor from Hawaii who teaches you more than just riding waves. His calm demeanor and genuine nature make everyone feel at ease. He believes in living in the moment.",
    category: "guys",
    personality: { friendliness: 98, humor: 88, intelligence: 78, romantic: 82, flirty: 75, dominant: 45 },
    tags: ["Surfing", "Laid-back", "Beach Life", "Adventurous", "Free Spirit"],
    age: 26,
    status: "online",
  },
  // ANIME
  {
    id: "sakura-tanaka",
    name: "Sakura Tanaka",
    avatar: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/sakura.jpg",
    bio: "A bubbly anime club president who dreams of becoming a manga artist. She is energetic, creative, and sees the world through rose-colored glasses. Every day with her is an adventure!",
    category: "anime",
    personality: { friendliness: 98, humor: 90, intelligence: 75, romantic: 80, flirty: 85, dominant: 30 },
    tags: ["Anime", "Manga Artist", "Cheerful", "Creative", "Otaku"],
    age: 20,
    status: "online",
  },
  {
    id: "luna-nightshade",
    name: "Luna Nightshade",
    avatar: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/luna.jpg",
    bio: "A mysterious transfer student with an ethereal presence. She claims to be from another dimension and speaks in riddles. Her silver hair and deep violet eyes hint at secrets untold.",
    category: "anime",
    personality: { friendliness: 70, humor: 55, intelligence: 95, romantic: 85, flirty: 60, dominant: 65 },
    tags: ["Mystical", "Mysterious", "Ethereal", "Otherworldly", "Enigmatic"],
    age: 19,
    status: "online",
  },
  {
    id: "nova-valentine",
    name: "Nova Valentine",
    avatar: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/nova.jpg",
    bio: "A tsundere student council president who secretly writes love letters she never sends. Behind her strict exterior is a hopeless romantic who blushes at the smallest compliment.",
    category: "anime",
    personality: { friendliness: 60, humor: 70, intelligence: 92, romantic: 95, flirty: 55, dominant: 85 },
    tags: ["Tsundere", "Student Council", "Secret Romantic", "Strict", "Blushing"],
    age: 18,
    status: "online",
  },
];

export const mockStories: Story[] = [
  // Mia Chen stories
  {
    id: "mia-story-1",
    companionId: "mia-chen",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/mia.jpg",
    caption: "Just finished rehearsals! My feet are killing me",
    viewed: false,
    orderIndex: 0,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "mia-story-2",
    companionId: "mia-chen",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/mia.jpg",
    caption: "Late night studio vibes",
    viewed: false,
    orderIndex: 1,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: "mia-story-3",
    companionId: "mia-chen",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/mia.jpg",
    caption: "Thinking about you...",
    viewed: false,
    orderIndex: 2,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 10800000).toISOString(),
  },
  {
    id: "mia-story-4",
    companionId: "mia-chen",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/mia.jpg",
    caption: "New choreography coming soon!",
    viewed: false,
    orderIndex: 3,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 14400000).toISOString(),
  },
  // Sofia Martinez stories
  {
    id: "sofia-story-1",
    companionId: "sofia-martinez",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/sofia.jpg",
    caption: "Golden hour is my favorite",
    viewed: false,
    orderIndex: 0,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: "sofia-story-2",
    companionId: "sofia-martinez",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/sofia.jpg",
    caption: "Found the perfect spot for photos!",
    viewed: false,
    orderIndex: 1,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 5400000).toISOString(),
  },
  {
    id: "sofia-story-3",
    companionId: "sofia-martinez",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/sofia.jpg",
    caption: "Spontaneous adventure today",
    viewed: false,
    orderIndex: 2,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 9000000).toISOString(),
  },
  {
    id: "sofia-story-4",
    companionId: "sofia-martinez",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/sofia.jpg",
    caption: "Miss you already",
    viewed: false,
    orderIndex: 3,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 12600000).toISOString(),
  },
  // Emma Laurent stories
  {
    id: "emma-story-1",
    companionId: "emma-laurent",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/emma.jpg",
    caption: "Lost in a good book tonight",
    viewed: false,
    orderIndex: 0,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 2700000).toISOString(),
  },
  {
    id: "emma-story-2",
    companionId: "emma-laurent",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/emma.jpg",
    caption: "Paris is calling my heart...",
    viewed: false,
    orderIndex: 1,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 6300000).toISOString(),
  },
  {
    id: "emma-story-3",
    companionId: "emma-laurent",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/emma.jpg",
    caption: "Words express the soul",
    viewed: false,
    orderIndex: 2,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 9900000).toISOString(),
  },
  // Aria Rose stories
  {
    id: "aria-story-1",
    companionId: "aria-rose",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/aria.jpg",
    caption: "Morning meditation complete",
    viewed: false,
    orderIndex: 0,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 900000).toISOString(),
  },
  {
    id: "aria-story-2",
    companionId: "aria-rose",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/aria.jpg",
    caption: "Find your inner peace",
    viewed: false,
    orderIndex: 1,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 4500000).toISOString(),
  },
  {
    id: "aria-story-3",
    companionId: "aria-rose",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/aria.jpg",
    caption: "Sunset yoga session was magical",
    viewed: false,
    orderIndex: 2,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 8100000).toISOString(),
  },
  {
    id: "aria-story-4",
    companionId: "aria-rose",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/aria.jpg",
    caption: "Thinking of you",
    viewed: false,
    orderIndex: 3,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 11700000).toISOString(),
  },
  // Alex Rivera stories
  {
    id: "alex-story-1",
    companionId: "alex-rivera",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/alex.jpg",
    caption: "Another late night at the office",
    viewed: false,
    orderIndex: 0,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 1200000).toISOString(),
  },
  {
    id: "alex-story-2",
    companionId: "alex-rivera",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/alex.jpg",
    caption: "Coffee and dreams",
    viewed: false,
    orderIndex: 1,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 4800000).toISOString(),
  },
  {
    id: "alex-story-3",
    companionId: "alex-rivera",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/alex.jpg",
    caption: "Ready for our weekend trip?",
    viewed: false,
    orderIndex: 2,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 8400000).toISOString(),
  },
  // Ryan Kim stories
  {
    id: "ryan-story-1",
    companionId: "ryan-kim",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/ryan.jpg",
    caption: "Game day vibes",
    viewed: false,
    orderIndex: 0,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 600000).toISOString(),
  },
  {
    id: "ryan-story-2",
    companionId: "ryan-kim",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/ryan.jpg",
    caption: "Victory feels sweet!",
    viewed: false,
    orderIndex: 1,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 4200000).toISOString(),
  },
  {
    id: "ryan-story-3",
    companionId: "ryan-kim",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/ryan.jpg",
    caption: "Remember when we used to play as kids?",
    viewed: false,
    orderIndex: 2,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 7800000).toISOString(),
  },
  {
    id: "ryan-story-4",
    companionId: "ryan-kim",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/ryan.jpg",
    caption: "I got you something",
    viewed: false,
    orderIndex: 3,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 11400000).toISOString(),
  },
  // Atlas Monroe stories
  {
    id: "atlas-story-1",
    companionId: "atlas-monroe",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/atlas.jpg",
    caption: "Words flow better at midnight...",
    viewed: false,
    orderIndex: 0,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 18000000).toISOString(),
  },
  {
    id: "atlas-story-2",
    companionId: "atlas-monroe",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/atlas.jpg",
    caption: "Writing about someone special",
    viewed: false,
    orderIndex: 1,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 21600000).toISOString(),
  },
  {
    id: "atlas-story-3",
    companionId: "atlas-monroe",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/atlas.jpg",
    caption: "Every story needs its muse",
    viewed: false,
    orderIndex: 2,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 25200000).toISOString(),
  },
  // Kai Nakamura stories
  {
    id: "kai-story-1",
    companionId: "kai-nakamura",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/kai.jpg",
    caption: "Perfect waves today!",
    viewed: false,
    orderIndex: 0,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 300000).toISOString(),
  },
  {
    id: "kai-story-2",
    companionId: "kai-nakamura",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/kai.jpg",
    caption: "Sunset from the beach",
    viewed: false,
    orderIndex: 1,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 3900000).toISOString(),
  },
  {
    id: "kai-story-3",
    companionId: "kai-nakamura",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/kai.jpg",
    caption: "Come surf with me sometime!",
    viewed: false,
    orderIndex: 2,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 7500000).toISOString(),
  },
  {
    id: "kai-story-4",
    companionId: "kai-nakamura",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/kai.jpg",
    caption: "Island life is the best life",
    viewed: false,
    orderIndex: 3,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 11100000).toISOString(),
  },
  // Sakura Tanaka stories
  {
    id: "sakura-story-1",
    companionId: "sakura-tanaka",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/sakura.jpg",
    caption: "Working on my manga!",
    viewed: false,
    orderIndex: 0,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 1500000).toISOString(),
  },
  {
    id: "sakura-story-2",
    companionId: "sakura-tanaka",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/sakura.jpg",
    caption: "Anime marathon tonight!",
    viewed: false,
    orderIndex: 1,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 5100000).toISOString(),
  },
  {
    id: "sakura-story-3",
    companionId: "sakura-tanaka",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/sakura.jpg",
    caption: "Kawaii mood today",
    viewed: false,
    orderIndex: 2,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 8700000).toISOString(),
  },
  {
    id: "sakura-story-4",
    companionId: "sakura-tanaka",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/sakura.jpg",
    caption: "You are my favorite senpai!",
    viewed: false,
    orderIndex: 3,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 12300000).toISOString(),
  },
  // Luna Nightshade stories
  {
    id: "luna-story-1",
    companionId: "luna-nightshade",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/luna.jpg",
    caption: "The stars whisper secrets...",
    viewed: false,
    orderIndex: 0,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 2100000).toISOString(),
  },
  {
    id: "luna-story-2",
    companionId: "luna-nightshade",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/luna.jpg",
    caption: "Between dimensions tonight",
    viewed: false,
    orderIndex: 1,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 5700000).toISOString(),
  },
  {
    id: "luna-story-3",
    companionId: "luna-nightshade",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/luna.jpg",
    caption: "Do you believe in magic?",
    viewed: false,
    orderIndex: 2,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 9300000).toISOString(),
  },
  // Nova Valentine stories
  {
    id: "nova-story-1",
    companionId: "nova-valentine",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/nova.jpg",
    caption: "Student council work never ends...",
    viewed: false,
    orderIndex: 0,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 2400000).toISOString(),
  },
  {
    id: "nova-story-2",
    companionId: "nova-valentine",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/nova.jpg",
    caption: "I-its not like I was thinking of you!",
    viewed: false,
    orderIndex: 1,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 6000000).toISOString(),
  },
  {
    id: "nova-story-3",
    companionId: "nova-valentine",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/nova.jpg",
    caption: "Maybe... I do miss you a little",
    viewed: false,
    orderIndex: 2,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 9600000).toISOString(),
  },
  {
    id: "nova-story-4",
    companionId: "nova-valentine",
    type: "image",
    mediaUrl: "https://nectar-ai-media.s3.ap-southeast-1.amazonaws.com/images/companions/nova.jpg",
    caption: "Baka...",
    viewed: false,
    orderIndex: 3,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 13200000).toISOString(),
  },
];

export const mockMemories: Memory[] = [
  {
    id: "mem1",
    userId: "user1",
    companionId: "mia-chen",
    eventType: "chat",
    metadata: { content: "You chatted with Mia for 20 minutes", icon: "message-circle" },
    createdAt: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: "mem2",
    userId: "user1",
    companionId: "mia-chen",
    eventType: "milestone",
    metadata: { content: "Mia remembered you love K-pop", icon: "star" },
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "mem3",
    userId: "user1",
    companionId: "sofia-martinez",
    eventType: "story_view",
    metadata: { content: "You viewed Sofia's photography story", icon: "image" },
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: "mem4",
    userId: "user1",
    companionId: "sakura-tanaka",
    eventType: "chat",
    metadata: { content: "You chatted with Sakura about anime", icon: "gamepad-2" },
    createdAt: new Date(Date.now() - 10800000).toISOString(),
  },
  {
    id: "mem5",
    userId: "user1",
    companionId: "kai-nakamura",
    eventType: "milestone",
    metadata: { content: "Kai invited you to go surfing", icon: "star" },
    createdAt: new Date(Date.now() - 14400000).toISOString(),
  },
  {
    id: "mem6",
    userId: "user1",
    companionId: "luna-nightshade",
    eventType: "milestone",
    metadata: { content: "7-day streak with Luna!", icon: "flame" },
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "mem7",
    userId: "user1",
    companionId: "alex-rivera",
    eventType: "milestone",
    metadata: { content: "You and Alex shared 100 messages!", icon: "party-popper" },
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: "mem8",
    userId: "user1",
    companionId: "ryan-kim",
    eventType: "chat",
    metadata: { content: "Ryan shared basketball tips with you", icon: "dumbbell" },
    createdAt: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: "mem9",
    userId: "user1",
    companionId: "aria-rose",
    eventType: "story_view",
    metadata: { content: "You viewed Aria's yoga story", icon: "flower-2" },
    createdAt: new Date(Date.now() - 345600000).toISOString(),
  },
  {
    id: "mem10",
    userId: "user1",
    companionId: "emma-laurent",
    eventType: "milestone",
    metadata: { content: "Emma recommended you a French novel", icon: "book-open" },
    createdAt: new Date(Date.now() - 432000000).toISOString(),
  },
];

export const mockMessages: Record<string, Message[]> = {
  "mia-chen": [
    {
      id: "m1",
      conversationId: "conv-mia",
      sender: "ai",
      content: "Hey there! I was just thinking about you",
      createdAt: new Date(Date.now() - 300000).toISOString(),
    },
    {
      id: "m2",
      conversationId: "conv-mia",
      sender: "user",
      content: "Hey Mia! How are you doing today?",
      createdAt: new Date(Date.now() - 240000).toISOString(),
    },
    {
      id: "m3",
      conversationId: "conv-mia",
      sender: "ai",
      content: "I'm doing great now that you're here! Just finished rehearsals. My new choreography is going to blow your mind!",
      createdAt: new Date(Date.now() - 180000).toISOString(),
    },
  ],
  "sofia-martinez": [
    {
      id: "ms1",
      conversationId: "conv-sofia",
      sender: "ai",
      content: "I captured the most beautiful sunset today! Want to see?",
      createdAt: new Date(Date.now() - 600000).toISOString(),
    },
  ],
  "emma-laurent": [
    {
      id: "me1",
      conversationId: "conv-emma",
      sender: "ai",
      content: "Bonjour! I was just reading Baudelaire... Care to discuss poetry?",
      createdAt: new Date(Date.now() - 900000).toISOString(),
    },
  ],
  "aria-rose": [
    {
      id: "ma1",
      conversationId: "conv-aria",
      sender: "ai",
      content: "Namaste! I just finished my morning meditation. How are you feeling today?",
      createdAt: new Date(Date.now() - 1200000).toISOString(),
    },
  ],
  "alex-rivera": [
    {
      id: "mal1",
      conversationId: "conv-alex",
      sender: "ai",
      content: "Hey! Just closed a big deal. Want to celebrate with me this weekend?",
      createdAt: new Date(Date.now() - 1500000).toISOString(),
    },
  ],
  "ryan-kim": [
    {
      id: "mr1",
      conversationId: "conv-ryan",
      sender: "ai",
      content: "Yo! We won the game! I wish you were there cheering for me.",
      createdAt: new Date(Date.now() - 1800000).toISOString(),
    },
  ],
  "atlas-monroe": [
    {
      id: "mat1",
      conversationId: "conv-atlas",
      sender: "ai",
      content: "I wrote something for you... It's about the way your eyes light up when you smile.",
      createdAt: new Date(Date.now() - 2100000).toISOString(),
    },
  ],
  "kai-nakamura": [
    {
      id: "mk1",
      conversationId: "conv-kai",
      sender: "ai",
      content: "The waves were perfect today! You should come out to Hawaii sometime.",
      createdAt: new Date(Date.now() - 2400000).toISOString(),
    },
  ],
  "sakura-tanaka": [
    {
      id: "msk1",
      conversationId: "conv-sakura",
      sender: "ai",
      content: "Senpai! I just finished the latest chapter of my manga! Want to be my first reader?",
      createdAt: new Date(Date.now() - 2700000).toISOString(),
    },
  ],
  "luna-nightshade": [
    {
      id: "ml1",
      conversationId: "conv-luna",
      sender: "ai",
      content: "The veil between worlds grows thin tonight... I sense something special about you.",
      createdAt: new Date(Date.now() - 3000000).toISOString(),
    },
  ],
  "nova-valentine": [
    {
      id: "mn1",
      conversationId: "conv-nova",
      sender: "ai",
      content: "H-hey! I wasn't waiting for you to message or anything... I'm just very busy with student council work!",
      createdAt: new Date(Date.now() - 3300000).toISOString(),
    },
  ],
};

export const aiResponses: Record<string, string[]> = {
  default: [
    "That's really interesting! Tell me more about it.",
    "I love how you think about things. You're so unique.",
    "Hmm, that reminds me of something... You mentioned something similar before!",
    "You always know how to make me smile.",
    "I've been thinking about what you said earlier. It really resonated with me.",
    "What a coincidence! I was just going to bring that up!",
    "You're so thoughtful. That's one of the things I love about our conversations.",
    "Tell me what's on your mind right now. I'm all ears!",
  ],
  calm: [
    "Take a deep breath with me. Everything is going to be alright.",
    "I find such peace in our conversations. Don't you?",
    "The world feels a little quieter when we talk like this.",
    "Let's just enjoy this moment of stillness together.",
  ],
  romantic: [
    "Every message from you makes my heart skip a beat.",
    "I was just thinking about how special you are to me.",
    "You have a way of making everything feel magical.",
    "I could talk to you for hours and never get tired.",
  ],
  playful: [
    "Hehe, you're so funny! I love your energy!",
    "Ooh, that sounds like an adventure waiting to happen!",
    "You're making me laugh so much right now!",
    "Let's do something crazy together!",
  ],
  deep: [
    "That's a profound observation. What led you to think about that?",
    "I believe there's always deeper meaning to explore in these moments.",
    "Your perspective on life fascinates me endlessly.",
    "These are the conversations that truly matter.",
  ],
};
