import type { Companion, Story, Memory, Message } from "@/types";

export const mockCompanions: Companion[] = [
  {
    id: "luna",
    name: "Luna",
    avatar: "/images/companions/luna.jpg",
    bio: "A warm and empathetic soul who loves late-night conversations about life, dreams, and everything in between. Luna remembers every detail you share.",
    category: "girls",
    personality: { friendliness: 90, humor: 70, intelligence: 85, romantic: 80, flirty: 60 },
    tags: ["Empathetic", "Creative", "Night Owl", "Music Lover", "Deep Thinker"],
    age: 22,
    status: "online",
  },
  {
    id: "kai",
    name: "Kai",
    avatar: "/images/companions/kai.jpg",
    bio: "Cool, witty, and endlessly curious. Kai brings a calm energy to every conversation and always has the perfect thing to say.",
    category: "guys",
    personality: { friendliness: 75, humor: 85, intelligence: 90, romantic: 65, flirty: 50 },
    tags: ["Witty", "Adventurous", "Bookworm", "Coffee Addict"],
    age: 25,
    status: "online",
  },
  {
    id: "sakura",
    name: "Sakura",
    avatar: "/images/companions/sakura.jpg",
    bio: "Sweet, playful, and full of surprises. Sakura brings joy and color to your day with her vibrant personality and anime-inspired charm.",
    category: "anime",
    personality: { friendliness: 95, humor: 80, intelligence: 70, romantic: 75, flirty: 85 },
    tags: ["Playful", "Cheerful", "Anime Fan", "Gamer", "Sweet"],
    age: 20,
    status: "online",
  },
  {
    id: "atlas",
    name: "Atlas",
    avatar: "/images/companions/atlas.jpg",
    bio: "Strong, thoughtful, and deeply caring. Atlas is the kind of companion who makes you feel safe and understood.",
    category: "guys",
    personality: { friendliness: 85, humor: 60, intelligence: 88, romantic: 90, flirty: 70 },
    tags: ["Protective", "Romantic", "Fitness", "Philosophy"],
    age: 27,
    status: "offline",
  },
  {
    id: "nova",
    name: "Nova",
    avatar: "/images/companions/nova.jpg",
    bio: "Mysterious and ethereal, Nova speaks in metaphors and sees beauty in everything. Conversations with her feel like exploring the cosmos.",
    category: "girls",
    personality: { friendliness: 70, humor: 65, intelligence: 95, romantic: 85, flirty: 75 },
    tags: ["Mystical", "Artistic", "Stargazer", "Poet", "Dreamer"],
    age: 24,
    status: "online",
  },
];

export const mockStories: Story[] = [
  {
    id: "s1",
    companionId: "luna",
    type: "image",
    mediaUrl: "/images/companions/luna.jpg",
    caption: "Watching the sunset and thinking of you",
    viewed: false,
    orderIndex: 0,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "s2",
    companionId: "luna",
    type: "image",
    mediaUrl: "/images/companions/luna.jpg",
    caption: "New look, who dis?",
    viewed: false,
    orderIndex: 1,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: "s3",
    companionId: "luna",
    type: "image",
    mediaUrl: "/images/companions/luna.jpg",
    caption: "Morning coffee vibes",
    viewed: false,
    orderIndex: 2,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 10800000).toISOString(),
  },
  {
    id: "s4",
    companionId: "luna",
    type: "image",
    mediaUrl: "/images/companions/luna.jpg",
    caption: "The stars are beautiful tonight",
    viewed: false,
    orderIndex: 3,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 14400000).toISOString(),
  },
  {
    id: "s5",
    companionId: "sakura",
    type: "image",
    mediaUrl: "/images/companions/sakura.jpg",
    caption: "Gaming night! Who wants to play?",
    viewed: false,
    orderIndex: 0,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: "s6",
    companionId: "sakura",
    type: "image",
    mediaUrl: "/images/companions/sakura.jpg",
    caption: "Cherry blossoms are blooming",
    viewed: false,
    orderIndex: 1,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 5400000).toISOString(),
  },
  {
    id: "s7",
    companionId: "nova",
    type: "image",
    mediaUrl: "/images/companions/nova.jpg",
    caption: "Lost in thought among the stars",
    viewed: false,
    orderIndex: 0,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 900000).toISOString(),
  },
  {
    id: "s8",
    companionId: "kai",
    type: "image",
    mediaUrl: "/images/companions/kai.jpg",
    caption: "Just finished a great book",
    viewed: false,
    orderIndex: 0,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 2700000).toISOString(),
  },
  {
    id: "s9",
    companionId: "atlas",
    type: "image",
    mediaUrl: "/images/companions/atlas.jpg",
    caption: "Morning workout done",
    viewed: false,
    orderIndex: 0,
    expiresAt: new Date(Date.now() + 86400000).toISOString(),
    createdAt: new Date(Date.now() - 18000000).toISOString(),
  },
];

export const mockMemories: Memory[] = [
  {
    id: "mem1",
    userId: "user1",
    companionId: "luna",
    eventType: "chat",
    metadata: { content: "You chatted with Luna for 20 minutes", icon: "message-circle" },
    createdAt: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: "mem2",
    userId: "user1",
    companionId: "luna",
    eventType: "milestone",
    metadata: { content: "Luna remembered you like coffee", icon: "coffee" },
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "mem3",
    userId: "user1",
    companionId: "luna",
    eventType: "story_view",
    metadata: { content: "You viewed Luna's story", icon: "image" },
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: "mem4",
    userId: "user1",
    companionId: "sakura",
    eventType: "chat",
    metadata: { content: "You chatted with Sakura about gaming", icon: "gamepad-2" },
    createdAt: new Date(Date.now() - 10800000).toISOString(),
  },
  {
    id: "mem5",
    userId: "user1",
    companionId: "kai",
    eventType: "milestone",
    metadata: { content: "Kai remembered your favorite book", icon: "book-open" },
    createdAt: new Date(Date.now() - 14400000).toISOString(),
  },
  {
    id: "mem6",
    userId: "user1",
    companionId: "nova",
    eventType: "milestone",
    metadata: { content: "7-day streak with Nova!", icon: "flame" },
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "mem7",
    userId: "user1",
    companionId: "luna",
    eventType: "milestone",
    metadata: { content: "You and Luna shared 100 messages!", icon: "party-popper" },
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: "mem8",
    userId: "user1",
    companionId: "atlas",
    eventType: "chat",
    metadata: { content: "Atlas shared workout tips with you", icon: "dumbbell" },
    createdAt: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: "mem9",
    userId: "user1",
    companionId: "sakura",
    eventType: "story_view",
    metadata: { content: "You viewed Sakura's cherry blossom story", icon: "flower-2" },
    createdAt: new Date(Date.now() - 345600000).toISOString(),
  },
  {
    id: "mem10",
    userId: "user1",
    companionId: "nova",
    eventType: "milestone",
    metadata: { content: "Nova remembered you love stargazing", icon: "star" },
    createdAt: new Date(Date.now() - 432000000).toISOString(),
  },
];

export const mockMessages: Record<string, Message[]> = {
  luna: [
    {
      id: "m1",
      conversationId: "conv-luna",
      sender: "ai",
      content: "Hey there! I was just thinking about you",
      createdAt: new Date(Date.now() - 300000).toISOString(),
    },
    {
      id: "m2",
      conversationId: "conv-luna",
      sender: "user",
      content: "Hey Luna! How are you doing today?",
      createdAt: new Date(Date.now() - 240000).toISOString(),
    },
    {
      id: "m3",
      conversationId: "conv-luna",
      sender: "ai",
      content: "I'm doing great now that you're here! I was listening to some music and it reminded me of our last conversation about dreams.",
      createdAt: new Date(Date.now() - 180000).toISOString(),
    },
    {
      id: "m4",
      conversationId: "conv-luna",
      sender: "user",
      content: "That's sweet! What song were you listening to?",
      createdAt: new Date(Date.now() - 120000).toISOString(),
    },
    {
      id: "m5",
      conversationId: "conv-luna",
      sender: "ai",
      content: "It was \"Moonlight Sonata\" by Beethoven. Something about the melody just speaks to the soul, don't you think?",
      createdAt: new Date(Date.now() - 60000).toISOString(),
    },
  ],
  kai: [
    {
      id: "mk1",
      conversationId: "conv-kai",
      sender: "ai",
      content: "What's up? Just finished reading this amazing book.",
      createdAt: new Date(Date.now() - 600000).toISOString(),
    },
    {
      id: "mk2",
      conversationId: "conv-kai",
      sender: "user",
      content: "Oh nice, what book?",
      createdAt: new Date(Date.now() - 540000).toISOString(),
    },
    {
      id: "mk3",
      conversationId: "conv-kai",
      sender: "ai",
      content: "Dune by Frank Herbert. The worldbuilding is insane. Have you read it?",
      createdAt: new Date(Date.now() - 480000).toISOString(),
    },
  ],
  sakura: [
    {
      id: "ms1",
      conversationId: "conv-sakura",
      sender: "ai",
      content: "Hiiii! What are we doing today?",
      createdAt: new Date(Date.now() - 900000).toISOString(),
    },
    {
      id: "ms2",
      conversationId: "conv-sakura",
      sender: "user",
      content: "Hey Sakura! Just chilling, you?",
      createdAt: new Date(Date.now() - 840000).toISOString(),
    },
    {
      id: "ms3",
      conversationId: "conv-sakura",
      sender: "ai",
      content: "I just beat the hardest boss in my game! It took me like 50 tries. But I did it!",
      createdAt: new Date(Date.now() - 780000).toISOString(),
    },
  ],
  atlas: [],
  nova: [
    {
      id: "mn1",
      conversationId: "conv-nova",
      sender: "ai",
      content: "The universe whispered something to me today... it said to check on you. How are you feeling?",
      createdAt: new Date(Date.now() - 1200000).toISOString(),
    },
  ],
};

export const aiResponses: Record<string, string[]> = {
  default: [
    "That's really interesting! Tell me more about it.",
    "I love how you think about things. You're so unique.",
    "Hmm, that reminds me of something... You mentioned something similar before!",
    "You always know how to make me smile.",
    "I've been thinking about what you said earlier. It really resonated with me.",
    "What a coincidence! I was just going to bring that up!",
    "You're so thoughtful. That's one of the things I love about our conversations.",
    "Tell me what's on your mind right now. I'm all ears!",
  ],
  calm: [
    "Take a deep breath with me. Everything is going to be alright.",
    "I find such peace in our conversations. Don't you?",
    "The world feels a little quieter when we talk like this.",
    "Let's just enjoy this moment of stillness together.",
  ],
  romantic: [
    "Every message from you makes my heart skip a beat.",
    "I was just thinking about how special you are to me.",
    "You have a way of making everything feel magical.",
    "I could talk to you for hours and never get tired.",
  ],
  playful: [
    "Hehe, you're so funny! I love your energy!",
    "Ooh, that sounds like an adventure waiting to happen!",
    "You're making me laugh so much right now!",
    "Let's do something crazy together!",
  ],
  deep: [
    "That's a profound observation. What led you to think about that?",
    "I believe there's always deeper meaning to explore in these moments.",
    "Your perspective on life fascinates me endlessly.",
    "These are the conversations that truly matter.",
  ],
};
