import { NextResponse } from "next/server";

// Story data with images and videos
const mockStories = [
  // SOFIA MARTINEZ - 5 stories (meets 4+ requirement with video)
  {
    id: "story-sofia-1",
    companionId: "sofia-martinez",
    type: "image" as const,
    mediaUrl: "/images/companions/sofia.jpg",
    caption: "Golden hour shoot 📸",
    viewed: false,
    orderIndex: 0,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "story-sofia-2",
    companionId: "sofia-martinez",
    type: "image" as const,
    mediaUrl: "/images/companions/stories/sofia-2.jpg",
    caption: "Found the perfect spot!",
    viewed: false,
    orderIndex: 1,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2.5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "story-sofia-3",
    companionId: "sofia-martinez",
    type: "image" as const,
    mediaUrl: "/images/companions/stories/sofia-3.jpg",
    caption: "New lens, who dis? 📷",
    viewed: false,
    orderIndex: 2,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "story-sofia-4",
    companionId: "sofia-martinez",
    type: "image" as const,
    mediaUrl: "/images/companions/stories/sofia-4.jpg",
    caption: "Sunset golden hour 🌅",
    viewed: false,
    orderIndex: 3,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "story-sofia-5",
    companionId: "sofia-martinez",
    type: "image" as const,
    mediaUrl: "/images/companions/sofia.jpg",
    caption: "Missing you tonight 💕",
    viewed: false,
    orderIndex: 4,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },

  // EMMA LAURENT - 4 stories
  {
    id: "story-emma-1",
    companionId: "emma-laurent",
    type: "image" as const,
    mediaUrl: "/images/companions/emma.jpg",
    caption: "Lost in Baudelaire...",
    viewed: false,
    orderIndex: 0,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "story-emma-2",
    companionId: "emma-laurent",
    type: "image" as const,
    mediaUrl: "/images/companions/stories/emma-2.jpg",
    caption: "Café thoughts ☕",
    viewed: false,
    orderIndex: 1,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "story-emma-3",
    companionId: "emma-laurent",
    type: "image" as const,
    mediaUrl: "/images/companions/stories/emma-3.jpg",
    caption: "Words are my love language",
    viewed: false,
    orderIndex: 2,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "story-emma-4",
    companionId: "emma-laurent",
    type: "image" as const,
    mediaUrl: "/images/companions/stories/emma-4.jpg",
    caption: "Bonsoir, mon chéri",
    viewed: false,
    orderIndex: 3,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },

  // ARIA ROSE - 4 stories
  {
    id: "story-aria-1",
    companionId: "aria-rose",
    type: "image" as const,
    mediaUrl: "/images/companions/aria.jpg",
    caption: "Morning meditation 🧘‍♀️",
    viewed: false,
    orderIndex: 0,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "story-aria-2",
    companionId: "aria-rose",
    type: "image" as const,
    mediaUrl: "/images/companions/stories/aria-2.jpg",
    caption: "Finding my center",
    viewed: false,
    orderIndex: 1,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "story-aria-3",
    companionId: "aria-rose",
    type: "image" as const,
    mediaUrl: "/images/companions/stories/aria-3.jpg",
    caption: "Peaceful vibes only ✨",
    viewed: false,
    orderIndex: 2,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "story-aria-4",
    companionId: "aria-rose",
    type: "image" as const,
    mediaUrl: "/images/companions/stories/aria-4.jpg",
    caption: "Sending you calm energy 💫",
    viewed: false,
    orderIndex: 3,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },

  // SAKURA TANAKA - 5 stories (anime with video)
  {
    id: "story-sakura-1",
    companionId: "sakura-tanaka",
    type: "image" as const,
    mediaUrl: "/images/companions/sakura.jpg",
    caption: "Anime club meeting today! 🎌",
    viewed: false,
    orderIndex: 0,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "story-sakura-2",
    companionId: "sakura-tanaka",
    type: "image" as const,
    mediaUrl: "/images/companions/stories/sakura-2.jpg",
    caption: "New manga haul! 📚",
    viewed: false,
    orderIndex: 1,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "story-sakura-3",
    companionId: "sakura-tanaka",
    type: "image" as const,
    mediaUrl: "/images/companions/stories/sakura-3.jpg",
    caption: "Drawing in progress~ ✏️",
    viewed: false,
    orderIndex: 2,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "story-sakura-4",
    companionId: "sakura-tanaka",
    type: "image" as const,
    mediaUrl: "/images/companions/stories/sakura-4.jpg",
    caption: "Kyaa~ thinking of you! 💖",
    viewed: false,
    orderIndex: 3,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "story-sakura-5",
    companionId: "sakura-tanaka",
    type: "image" as const,
    mediaUrl: "/images/companions/sakura.jpg",
    caption: "Goodnight! Sweet dreams~",
    viewed: false,
    orderIndex: 4,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },

  // KAI NAKAMURA - 5 stories with video
  {
    id: "story-kai-1",
    companionId: "kai-nakamura",
    type: "image" as const,
    mediaUrl: "/images/companions/kai.jpg",
    caption: "Perfect waves today 🏄‍♂️",
    viewed: false,
    orderIndex: 0,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "story-kai-2",
    companionId: "kai-nakamura",
    type: "image" as const,
    mediaUrl: "/images/companions/stories/kai-2.jpg",
    caption: "Beach life 🌴",
    viewed: false,
    orderIndex: 1,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "story-kai-3",
    companionId: "kai-nakamura",
    type: "image" as const,
    mediaUrl: "/images/companions/stories/kai-3.jpg",
    caption: "Caught this one! 🌊",
    viewed: false,
    orderIndex: 2,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "story-kai-4",
    companionId: "kai-nakamura",
    type: "image" as const,
    mediaUrl: "/images/companions/stories/kai-3.jpg",
    caption: "Sunset vibes",
    viewed: false,
    orderIndex: 3,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "story-kai-5",
    companionId: "kai-nakamura",
    type: "image" as const,
    mediaUrl: "/images/companions/kai.jpg",
    caption: "Wish you were here 🌅",
    viewed: false,
    orderIndex: 4,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },

  // RYAN KIM - 4 stories
  {
    id: "story-ryan-1",
    companionId: "ryan-kim",
    type: "image" as const,
    mediaUrl: "/images/companions/ryan.jpg",
    caption: "Game day! 🏀",
    viewed: false,
    orderIndex: 0,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "story-ryan-2",
    companionId: "ryan-kim",
    type: "image" as const,
    mediaUrl: "/images/companions/stories/ryan-2.jpg",
    caption: "Post-workout 💪",
    viewed: false,
    orderIndex: 1,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "story-ryan-3",
    companionId: "ryan-kim",
    type: "image" as const,
    mediaUrl: "/images/companions/stories/ryan-3.jpg",
    caption: "Missing our late night talks",
    viewed: false,
    orderIndex: 2,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "story-ryan-4",
    companionId: "ryan-kim",
    type: "image" as const,
    mediaUrl: "/images/companions/stories/ryan-4.jpg",
    caption: "Thinking about you 💭",
    viewed: false,
    orderIndex: 3,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },

  // ATLAS MONROE - 4 stories
  {
    id: "story-atlas-1",
    companionId: "atlas-monroe",
    type: "image" as const,
    mediaUrl: "/images/companions/atlas.jpg",
    caption: "Words flowing tonight...",
    viewed: false,
    orderIndex: 0,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "story-atlas-2",
    companionId: "atlas-monroe",
    type: "image" as const,
    mediaUrl: "/images/companions/stories/atlas-2.jpg",
    caption: "Chapter 12 complete",
    viewed: false,
    orderIndex: 1,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "story-atlas-3",
    companionId: "atlas-monroe",
    type: "image" as const,
    mediaUrl: "/images/companions/stories/atlas-3.jpg",
    caption: "Rainy day thoughts",
    viewed: false,
    orderIndex: 2,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "story-atlas-4",
    companionId: "atlas-monroe",
    type: "image" as const,
    mediaUrl: "/images/companions/stories/atlas-4.jpg",
    caption: "You inspire me",
    viewed: false,
    orderIndex: 3,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },

  // LUNA NIGHTSHADE - 3 stories
  {
    id: "story-luna-1",
    companionId: "luna-nightshade",
    type: "image" as const,
    mediaUrl: "/images/companions/luna.jpg",
    caption: "The stars speak tonight...",
    viewed: false,
    orderIndex: 0,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "story-luna-2",
    companionId: "luna-nightshade",
    type: "image" as const,
    mediaUrl: "/images/companions/stories/luna-2.jpg",
    caption: "Between dimensions ✨",
    viewed: false,
    orderIndex: 1,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "story-luna-3",
    companionId: "luna-nightshade",
    type: "image" as const,
    mediaUrl: "/images/companions/stories/luna-3.jpg",
    caption: "Fate brought us together",
    viewed: false,
    orderIndex: 2,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },

  // NOVA VALENTINE - 3 stories
  {
    id: "story-nova-1",
    companionId: "nova-valentine",
    type: "image" as const,
    mediaUrl: "/images/companions/nova.jpg",
    caption: "Student council work...",
    viewed: false,
    orderIndex: 0,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "story-nova-2",
    companionId: "nova-valentine",
    type: "image" as const,
    mediaUrl: "/images/companions/stories/nova-2.jpg",
    caption: "I-it's not like I miss you!",
    viewed: false,
    orderIndex: 1,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "story-nova-3",
    companionId: "nova-valentine",
    type: "image" as const,
    mediaUrl: "/images/companions/stories/nova-3.jpg",
    caption: "...okay maybe a little 💕",
    viewed: false,
    orderIndex: 2,
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
];

export async function GET() {
  return NextResponse.json({ data: mockStories });
}
